# Generated by Django 5.1.6 on 2025-02-26 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do fornecedor.', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='E-mail do fornecedor.', max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone do fornecedor.', max_length=15)),
                ('endereco', models.CharField(blank=True, help_text='Endereço do fornecedor.', max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional sobre o fornecedor.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
