# Generated by Django 5.1.6 on 2025-02-26 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bens', '0001_initial'),
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da movimentação.')),
                ('tipo_movimentacao', models.CharField(choices=[('Transferência', 'Transferência'), ('Alteração de Status', 'Alteração de Status'), ('Manutenção', 'Manutenção'), ('Desativação', 'Desativação')], help_text='Tipo de movimentação realizada.', max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional sobre a movimentação.')),
                ('status_anterior', models.CharField(blank=True, help_text='Status anterior do bem antes da movimentação.', max_length=50)),
                ('status_atual', models.CharField(blank=True, help_text='Status atual do bem após a movimentação.', max_length=50)),
                ('bem', models.ForeignKey(help_text='Bem que está sendo movimentado.', on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='bens.bem')),
                ('departamento_destino', models.ForeignKey(blank=True, help_text='Departamento de destino da movimentação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='departamentos.departamento')),
                ('departamento_origem', models.ForeignKey(blank=True, help_text='Departamento de origem da movimentação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='departamentos.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
