# Generated by Django 5.1.6 on 2025-02-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do bem.', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do bem.')),
                ('rfid_codigo', models.CharField(blank=True, help_text='Código RFID do bem, se aplicável.', max_length=100)),
                ('data_aquisicao', models.DateField(help_text='Data de aquisição do bem.')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do bem.', max_digits=10)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Em manutenção', 'Em manutenção')], default='Ativo', help_text='Status do bem.', max_length=50)),
                ('categoria', models.ForeignKey(help_text='Categoria do bem.', on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='categorias.categoria')),
                ('departamento', models.ForeignKey(help_text='Departamento onde o bem está alocado.', on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='departamentos.departamento')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Fornecedor do bem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens', to='fornecedores.fornecedor')),
            ],
        ),
    ]
