# Generated by Django 5.1.6 on 2025-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do departamento, como TI, RH, etc.', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do departamento.')),
            ],
        ),
    ]
